{application,resend,
             [{optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,swoosh,tesla,
                             hackney]},
              {description,"API client for Resend, the new email API for developers."},
              {modules,['Elixir.Resend','Elixir.Resend.ApiKeys',
                        'Elixir.Resend.ApiKeys.ApiKey',
                        'Elixir.Resend.Castable','Elixir.Resend.Client',
                        'Elixir.Resend.Client.TeslaClient',
                        'Elixir.Resend.Domains',
                        'Elixir.Resend.Domains.Domain',
                        'Elixir.Resend.Domains.Domain.Record',
                        'Elixir.Resend.Emails','Elixir.Resend.Emails.Email',
                        'Elixir.Resend.Empty','Elixir.Resend.Error',
                        'Elixir.Resend.List','Elixir.Resend.Swoosh.Adapter',
                        'Elixir.Resend.Util']},
              {registered,[]},
              {vsn,"0.4.1"}]}.
